config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  get 'coaching-panel' => 'pages#coaching_panel'
  get 'committee' => 'pages#committee'
  get 'news' => 'posts#index'

  devise_for :users
  resources :posts

  root 'pages#home'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/committee_member.rb
class CommitteeMember
  attr_accessor :name, :intro, :position, :image_link

  def initialize(name, intro, position)
    @name = name
    @intro = intro
    @position = position
    @image_link = name.downcase.gsub(/[^0-9a-z]/i, '')
  end

  def self.get_all_members
    YAML.load_file('config/users.yml').map do |name, details|
      new(name, details['intro'], details['position'])
    end
  end
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
  # commented out due to chartkick + Postgresql error
  # default_scope :order=>'created_at DESC'
  has_many :taggings
  has_many :tags, through: :taggings
  
  def to_param
    "#{id} #{title}".parameterize
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).articles
  end

  def self.tag_counts
    Tag.select("tags.id, tags.name, count(taggings.tag_id) as count").
      joins(:taggings).group("taggings.tag_id, tags.id, tags.name")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/models/pygmentizer.rb
require 'pygments'

class Pygmentizer < Redcarpet::Render::HTML
  def block_code(code, language)
    Pygments.highlight(code, lexer: language)
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :taggings
    has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, 
    :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    render layout: 'home'
  end

  def coaching_panel
  end

  def committee
    @alignments = %w(left right)
    @committee_members = CommitteeMember.get_all_members
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts =
      if params[:tag] && params[:tag].present? && params[:tag] != 'null'
        @react_params = params[:tag]
        Post.tagged_with(params[:tag])
      else
        Post.all
      end.order(created_at: :desc)
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to root_path, notice: 'post was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'post was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Pygmentizer
    options = {
      filter_html: false,
      hard_wrap: true,
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true,
      tables: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UCSC</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, minimal-ui">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body data-spy="scroll" data-target="home-top-navbar">
  <div class="container-fluid">
    <%= render 'shared/xl_menu' %>

    <div class="row">
      <%= render 'shared/menu' %>
      <%= yield %>
    </div>
  </div>
  <%= render 'shared/ga_tracking' %>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UCSC</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, minimal-ui">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body data-spy="scroll" data-target="home-top-navbar">

  <div class="container-fluid" id="fullpage">
    <%= render 'shared/xl_menu' %>

    <div class="row">
      <%= render 'shared/menu' %>
    </div>

    <div class="row masthead-container">
      <div class="masthead parallax-1 section" id="masthead">
        <div class="masthead-hero">
          <h1 class="header masthead-hero--ucsc">United Condo Squash Club</h1>
          <h2 class="header masthead-hero--slogan">LIVE AND BREATHE SQUASH</h2>
        </div>
      </div>

      <div class="masthead-links--angle-down">
        <a href="#about-us">
          <span class="fa fa-chevron-circle-down"></span>
        </a>
      </div>
    </div>

    <div class="row">
      <div class="masthead-links-container col-xs-12">
        <div class="masthead-links--sponsors row">
          <div class="col-xs-12">
          </div>
          <div class="col-xs-12 col-md-offset-1 col-md-10">
            <div class="row">
              <div class="col-xs-12 col-md-3 sponsors--sponsored-by">
                <p> Proudly Sponsored By: </p>
              </div>
              <div class="col-xs-12 col-md-3 sponsors--orchard-physio"></div>
              <div class="col-xs-12 col-md-3 sponsors--indusnri"></div>
              <div class="col-xs-12 col-md-3 sponsors--gene-ethics"></div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <%= yield %>
  </div>
  <%= render 'shared/footer' %>

  <%= render 'shared/ga_tracking' %>
</body>
</html>

app/views/pages/_club_about_us.html.erb
<div class="col-xs-12 col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
  <h2 class="header club-info--section-header">
    About Us
  </h2>
  <p class="club-about-us--text">
  The United Condo Squash Club (UCSC) was founded in 1997 and has been one of Singapore's most active and successful squash clubs. The Club is funded through membership fees and plays at public courts. Competitive playing members participate in the Singapore National Squash League annually. UCSC has won the "Club of the Year" title on several occasions and boasts of having contributed to providing Singapore with a significant number of top national players who have achieved notable regional success. </p>

  <p class="club-about-us--text">
    There are plenty of opportunities for competitive squash at all levels whilst the Club strives to create an environment where members are able to also socialize.
  </p>

  <p class="club-about-us--text">
    If you have competitive playing experience and are interested to become a UCSC member, please do reach out to the UCSC Management Committee. Contact details may be found <a href="/#club-contact-us">here</a>. Please be prepared for a warm friendly greeting!
  </p>

  <p class="club-about-us--text">
    UCSC Lives & Breathes Squash!
  </p>
</div>

app/views/pages/_club_committee.html.erb
<div class="club-info--club-committee club-info--section">
  <div class="club-info--section-icons">
    <i class="huge child icon"></i>
  </div>

  <div class="club-committee--text">
    <h2 class="header club-info--section-header">Our Committee Members</h2>
  </div>

  <div class="club-committee--pictures">
    <% @committee_members.each do |name| %>
      <div class="club-committee--picture-circle">
        <%= name %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/_club_contacts.html.erb
<div class="club-info--club-contacts club-info--section">
  <h2 class="header club-info--section-header">Contact Us</h2>
  <div class="club-info--social">
    <a href="https://www.facebook.com/UCSCsingapore">
      <span class="fa-stack fa-2x">
        <i class="fa fa-circle fa-stack-2x"></i>
        <i class="fa fa-facebook-f fa-stack-1x fa-inverse"></i>
      </span>
    </a>
  </div>
  <iframe 
      src="https://docs.google.com/forms/d/e/1FAIpQLSdM5VeuV3j0PWlZoczVg3ZkTRKaTHtVyNSUzJwxo625P12HuQ/viewform?embedded=true" 
      width="100%" 
      height="1440" 
      frameborder="0" 
      marginheight="0" 
      marginwidth="0">
    Loading...
  </iframe>
</div>

app/views/pages/_club_location.html.erb
<div class="col-xs-12 col-md-offset-1 col-md-4">
  <h2 class="header club-info--section-header club-location--section-header">
    Home Courts
  </h2>
  <p>
    Members are invited to come down on any of the social squash days. 
    Those who are looking to play competitively are also encouraged to represent the club in the Singapore National Squash League. 
  </p>
</div>

<div class="col-xs-12 col-md-offset-1 col-md-6 club-location--overlay">
  <div class="row club-location--text">
    <div class="col-xs-12 col-lg-10">
      <div class="club-location--card card card-block">
        <%= icon 'map-marker', class: 'fa-2x' %>
        <h4 class="card-title">Methodist Girls' School</h4>
        <br>
        <p class="card-text">
          Thursdays: 7pm to 10pm
        </p>
        <p class="card-text">
          Saturdays: 12pm to 4pm
        </p>
      </div>
    </div>
  </div>
</div>

app/views/pages/_club_membership.html.erb
<div class="col-xs-12 col-lg-offset-1 col-lg-10 col-xl-offset-2 col-xl-8">
  <h2 class="header club-info--section-header">
    Join us!
  </h2>

  <div class="col-xs-12 col-md-4">
    <h4 class="header club-info--section-sub-header">
      Annual Membership
    </h4>
    <p>
      All court fees and registration fees are included in the annual membership fee of 
      $125 for Students and $250 for Adults
    </p>
  </div>

  <div class="col-xs-12 col-md-4">
    <h4 class="header club-info--section-sub-header">Guest Pass</h4>
    <p>
      Non-members are welcome to join us on any of the social squash days at a fee of $20. 
      Do drop us an email to let us know beforehand so that we can make the necessary arrangements.
    </p>
  </div>

  <div class="col-xs-12 col-md-4">
    <h4 class="header club-info--section-sub-header">Trials</h4>
    <p>
      If you have prior squash experience and are interested in joining us, 
      feel free to contact us and we will arrange a session for you!
    </p>
  </div>
</div>

app/views/pages/coaching_panel.html.erb
<div class="container-fluid coaching-panel--container">
  <div class="col-xs-12">

    <div class="row">
      <h1 class="page-main-header">Coaching Panel</h1>
      <p class="page-introduction">
        Resident coaches of UCSC
      </p>
    </div>

    <div class="row coaching-panel--coaches">
      <div class="col-xs-12 col-md-4">
        <div class="card coaches--coach-details">
          <div class="card-block">
            <h4 class="card-title">Simon Yang</h4>
            <h6 class="card-subtitle text-muted">National Coach, Indonesia</h6>
          </div>
          <div class="card-block">
            <p class="card-text">UCSC member since 2005</p>
            <p class="card-text">Playing experience since 1984</p>
            <p class="card-text">Coaching experience since 1990</p>
            <a href="https://drive.google.com/open?id=0B6es4VmG9tzFSGJiQnIyNmhRU1I2NUNlTkRwNTNaWm94RGI0" class="card-link" target="_blank">CV - Simon Yang</a>
          </div>
        </div>
      </div>

      <div class="col-xs-12 col-md-4">
        <div class="card coaches--coach-details">
          <div class="card-block">
            <h4 class="card-title">Francis Wong</h4>
            <h6 class="card-subtitle text-muted">Coach - NYP, NJC</h6>
          </div>
          <div class="card-block">
            <p class="card-text">UCSC member since 1997</p>
            <p class="card-text">Playing experience since 1989</p>
            <p class="card-text">Coaching experience since 1996</p>
          </div>
        </div>
      </div>

      <div class="col-xs-12 col-md-4">
        <div class="card coaches--coach-details">
          <div class="card-block">
            <h4 class="card-title">Philip Mockridge</h4>
            <h6 class="card-subtitle text-muted">Winner of Singapore Masters, 2014</h6>
          </div>
          <div class="card-block">
            <p class="card-text">For more information, kindly visit his coaching site below:</p>
            <a href="http://www.squashpassion.com" class="card-link">Squash Passion</a>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/pages/committee.html.erb
<div class="container committee--container">
  <div class="col-xs-12 col-md-offset-1 col-md-10 col-xl-offset-2 col-xl-8">

    <div class="row">
      <h1 class="page-main-header">Our Committee</h1>
    </div>

    <div class="committee-members">
      <% @committee_members.each_with_index do |committee_member, index| %>
        <% align = @alignments[index % 2]%>

        <div class="row committee-member">
          <div class="col-xs-12 col-md-3">
            <div class="row committee-member--small-image-holder">
              <div class="col-xs-6 col-md-12">
                <%= image_tag("#{committee_member.image_link}.jpg", width: '130', class: "committee-member--image") %>
              </div>
              <div class="hidden-md-up col-xs-6">
                <p class="committee-member--name"><%= committee_member.name %></p>
                <p class="committee-member--position"><%= committee_member.position %></p>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-md-9 pull-<%= @alignments[index % 2 - 1] %>">
            <div class="committee-member--block">
              <p class="hidden-md-down committee-member--name"><%= committee_member.name %></p>
              <p class="hidden-md-down committee-member--position"><%= committee_member.position %></p>
              <p class="committee-member--intro"><%= committee_member.intro %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-xs-12 club-info">
    <div class="row club-info--about-us club-info--section" id="about-us">
      <%= render 'club_about_us' %>
    </div>

    <div class="col-lg-12" id="club-location"></div>
    <div class="club-info--club-location club-info--section row">
      <%= render 'club_location' %>
    </div>

    <div class="col-lg-12" id="club-membership"></div>
    <div class="row club-info--club-membership club-info--section">
      <%= render 'club_membership' %>
    </div>

    <div class="col-lg-12" id="club-contact-us"></div>
    <div class="row club-info--contact-us club-info--section">
      <%= render 'club_contacts' %>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for(@post, html: { class: 'form-horizontal' }) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title, as: :text %>
  <%= f.input :content, as: :text, input_html: { rows: 20 } %>

  <div class="actions">
    <%= f.submit 'Publish', class: 'btn btn-success'%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container posts--container">
  <div class="col-xs-12 col-md-offset-1 col-md-10 col-xl-offset-2 col-xl-8">

    <div class="row new-post-btn--container">
      <div class="col-xs-12">
        <%= link_to 'Show', @post %> |
        <%= link_to 'Back', posts_path %>
      </div>
    </div>

    <%= render 'form' %>
    <br>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container-fluid posts--container">
  <div class="col-xs-12 col-md-offset-2 col-md-8 col-xl-offset-3 col-xl-6">
    <% if user_signed_in? && current_user.has_role?(:admin) %>
      <div class="row new-post-btn--container">
        <div class="col-xs-12">
          <%= link_to new_post_path do %>
            New Post
          <% end %>
        </div>
      </div>
    <% end %>

    <%# <%= react_component('PostsBox', url: '/posts.json', react_params: @react_params) %1> %>

    <div class="posts">
      <% @posts.each do |post| %>
        <div class="post">
          <div class="posts--post-summary">
            <h2 class="post-summary--post-title">
              <a href=<%= post_path(post) %> class="post-summary--post-link">
                <%= post.title %>
              </a>
              <p class="post-summary--post-time muted">
                <%= post.created_at.in_time_zone('Singapore').strftime("%B %d") %>
              </p>
            </h2>
            <div class="post-summary--post-synopsis">
              <%= markdown post.content.truncate(350) %>
              <%= link_to 'Read more', post_path(post) %>
            </p> 
            <br>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container posts--container">
  <div class="col-xs-12 col-md-offset-1 col-md-10 col-xl-offset-2 col-xl-8">
      <div class="row new-post-btn--container">
        <div class="col-xs-12">
          <%= link_to 'Back', posts_path %>
        </div>
      </div>
    <%= render 'form' %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container post--container">
  <div class="col-xs-12 col-md-offset-1 col-md-10">

    <div class="row edit-post-btn--container">
      <div class="col-xs-12">
        <% if user_signed_in? && current_user.has_role?(:admin) %>
          <%= link_to 'Edit', edit_post_path(@post) %> |
        <% end %>
        <%= link_to 'Back', posts_path %>
      </div>
    </div>

    <h1 class="page-main-header post--title">
      <%= @post.title %>
      <br><br>
      <p class="post--time muted">
        <%= @post.created_at.in_time_zone('Singapore').strftime("%B %d") %>
      </p>
    </h1>
    <div class="post--content">
      <%= markdown @post.content %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <p class="copyright">Copyright © 2017 Boa Ho Man. All rights reserved.</p>
</footer>

app/views/shared/_ga_tracking.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-72788030-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/shared/_menu.html.erb
<div class="col-xs-12 hidden-xl-up menu-toggler">
  <button class="icon-menu navbar-toggler" type="button">
    <span class="fa fa-bars fa-inverse"></span>
  </button>
</div>

<nav class="large-navbar navbar navbar-minimalist navbar-fixed-top bg-inverse">
  <ul class="pull-xs-left nav navbar-nav navbar-minimalist nav-pills">
    <li class="nav-item">
      <a class="nav-link nav-link--home" href="/#masthead">UCSC</a>
    </li>
  </ul>
  <ul class="pull-xs-right nav navbar-nav navbar-minimalist nav-pills nav-pills--others">
    <li class="nav-item">
      <a class="nav-link" href="/#about-us">About Us</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/#club-location">Location</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/#club-membership">Membership</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/#club-contact-us">Contact Us</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/coaching-panel">Coaching Panel</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/committee">Committee</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/news">NSL News</a>
    </li>
    <li class="nav-item pull-right">
      <% if user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %>
      <% else %>
        <%= link_to 'Login', new_user_session_path, class: "nav-link" %>
      <% end %>
    </li>
  </ul>
</nav>

app/views/shared/_xl_menu.html.erb
<div class="full-menu hidden-xl-up">
  <ul class="nav nav-pills nav-stacked menu--links">
    <li class="nav-item">
      <a class="nav-link" href="/#masthead">UCSC</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/#about-us">About Us</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/#club-location">Location</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/#club-membership">Membership</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/#club-contact-us">Contact Us</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/coaching-panel">Coaching Panel</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/committee">Committee</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/news">NSL News</a>
    </li>
    <li class="nav-item">
      <% if user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %>
      <% else %>
        <%= link_to 'Login', new_user_session_path, class: "nav-link" %>
      <% end %>
    </li>
  </ul>
</div>